name: simplenotes
description: "Flutter project with notes."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  logger: ^2.3.0
  go_router: ^14.2.0
  flutter_lints: ^4.0.0
  dio: ^5.4.3+1
  flutter_localizations:
    sdk: flutter
  intl: any
  device_info_plus: ^9.1.2
  get_it: ^7.7.0
  equatable: ^2.0.5
  injectable: ^2.4.2
  remote_config: ^1.3.0+3
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9
  firebase_remote_config: ^4.3.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  integration_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true